program: sweep.py
method: grid
metric:
  goal: minimize
  name: overall_loss
parameters:
  epochs:
    value: 60
  learning_rate:
    value: 0.001
  a_mse:
    value: 0.15
  a_content:
    value: 0.0
  a_style:
    value: 0.0
  a_spst:
    value: 0.85
  content_layer:
    value: 1
  style_layer:
    value: 1  
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27