program: sweep.py
method: random
metric:
  goal: minimize
  name: overall_validation_loss
parameters:
  epochs: 
    value: 60
  content_layer:
    values: [1, 2, 3, 4, 5]
  style_layer:
    values: [1, 2, 3, 4, 5]
  a_mse:
    values: [0.05, 0.1, 0.3, 0.4]
  a_content:
    values: [0.05, 0.1, 0.3, 0.4]
  a_style:
    values: [0.1, 0.15, 0.3, 0.5, 0.7]
  a_spst:
    values: [0.2, 0.4, 0.6, 0.8] 
early_terminate:
  type: hyperband
  s: 4
  eta: 2
  min_iter: 10